daml-sdk-head also installs HEAD jars

diff --git a/dev-env/bin/daml-sdk-head b/dev-env/bin/daml-sdk-head
--- a/dev-env/bin/daml-sdk-head
+++ b/dev-env/bin/daml-sdk-head
@@ -95,3 +95,23 @@ chmod +x $DAML_HOME/bin/daml-head
 trap - EXIT
 echo "$(tput setaf 3)Successfully installed daml-head command.$(tput sgr 0)"
 
+echo "$(tput setaf 3)Installing JARs as 100.0.0...$(tput sgr 0)"
+
+cp "$REPO_ROOT/VERSION" "$REPO_ROOT/VERSION.head-build-in-progress"
+
+function cleanup() {
+  echo "$(tput setaf 3)FAILED TO INSTALL JARS! $(tput sgr 0)"
+  mv "$REPO_ROOT/VERSION.head-build-in-progress" "$REPO_ROOT/VERSION"
+}
+trap cleanup EXIT
+
+echo "0.0.0" > "$REPO_ROOT/VERSION"
+
+bazel build //release:release
+tmp=$(mktemp -d)
+"$REPO_ROOT/bazel-bin/release/release" --artifacts "$REPO_ROOT/release/artifacts.yaml" --release-dir $tmp --all-artifacts --install-head-jars
+
+mv "$REPO_ROOT/VERSION.head-build-in-progress" "$REPO_ROOT/VERSION"
+trap - EXIT
+
+echo "$(tput setaf 3)Done installing JARs as 100.0.0.$(tput sgr 0)"
